// <auto-generated />
using System;
using ChatApp.NotificationService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChatApp.NotificationService.Data.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    partial class NotificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChatApp.NotificationService.Entities.GroupMemberSnapshot", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("IsMember")
                        .HasColumnType("boolean")
                        .HasColumnName("is_member");

                    b.Property<DateTimeOffset>("LastEventAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_event_at");

                    b.Property<Guid>("LastEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_event_id");

                    b.HasKey("GroupId", "UserId")
                        .HasName("pk_group_member_snapshots");

                    b.ToTable("group_member_snapshots", (string)null);
                });

            modelBuilder.Entity("ChatApp.NotificationService.Entities.ProcessedEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("EventId")
                        .HasName("pk_processed_events");

                    b.ToTable("processed_events", (string)null);
                });

            modelBuilder.Entity("ChatApp.NotificationService.Entities.UnreadCounter", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<long>("LastReadSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_read_sequence");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("integer")
                        .HasColumnName("unread_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId", "GroupId")
                        .HasName("pk_unread_counters");

                    b.ToTable("unread_counters", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
